### ISSUE TITLE
Hi.I addCallback like this,but it's not call onCreate(), But onOpen() .it's have.Please tell me why.Thanks a  lot

### ISSUE THREAD

**Issue by HarryHaiVn** [humazed/RoomAsset#10]
return RoomAsset.databaseBuilder(appContext, AppDatabase.class, DATABASE_NAME)
                .addCallback(new Callback() {
                    @Override
                    public void onCreate(@NonNull SupportSQLiteDatabase db) {
                        super.onCreate(db);
                        Log.d("RoomAsset:------", "onCreate");
                    }

                    @Override
                    public void onOpen(@NonNull SupportSQLiteDatabase db) {
                        super.onOpen(db);
                        Log.d("RoomAsset:------", "onOpen");
                    }
                })
                .build();

**Comment by humazed** [comment]
Because the creation of the database and the migration happens before `onCreate` has a chance to be called.

so after the method `databaseBuilder` is called the database is guaranteed to be created and you can perform your logic there.

I'm curious, why you need to know when the DB is created?
