### ISSUE TITLE
How can I do migration using this library

### ISSUE THREAD

**Issue by a1993k** [humazed/RoomAsset#12]
I have one app with some pre-filled data.
now in-app update I need to replace the old DB file with the new one from the asset. 
Is it done by the library or I need to do extra effort?

**Comment by humazed** [comment]
It's not clear what do you mean by pre-filled data?
do you have the data in a .db file?

**Comment by a1993k** [comment]
yes there is data in db.
version 1 have some data for ex 1 table with 4 rows.
now version 5 have 6 rows then how can I do migration?

**Comment by humazed** [comment]
You just need to update your entities and increment database version

**Comment by humazed** [comment]
and use 
``` kotlin
  val db = RoomAsset.databaseBuilder(applicationContext, AppDatabase::class.java, "chinook.db")
        .fallbackToDestructiveMigration()
        .build()
```

**Comment by a1993k** [comment]
ok.
Thanks for your quick response.
I will check it out.
