### ISSUE TITLE
Failed database migration validation

### ISSUE THREAD

**Issue by MrLepage** [humazed/RoomAsset#4]
When I try to open the database for the first time with RoomAsset, the migration validation fails.
I see that the columns order is not the same between what is expected and what is found.
I don't know how the columns order are determined.

java.lang.IllegalStateException: Migration didn't properly handle products(com.garnier.garnier.manager.catalog.database.entities.Product).
                                                    
```
Expected: TableInfo{name='products', columns={description=Column{name='description', type='TEXT', notNull=false, primaryKeyPosition=0}, tutorialUrl=Column{name='tutorialUrl', type='TEXT', notNull=false, primaryKeyPosition=0}, id=Column{name='id', type='INTEGER', notNull=true, primaryKeyPosition=1}, eanBarcode=Column{name='eanBarcode', type='INTEGER', notNull=false, primaryKeyPosition=0}, brandId=Column{name='brandId', type='INTEGER', notNull=false, primaryKeyPosition=0}, name=Column{name='name', type='TEXT', notNull=false, primaryKeyPosition=0}, shadeId=Column{name='shadeId', type='INTEGER', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=[]}
```
                                                  
```
Found: TableInfo{name='products', columns={tutorialURL=Column{name='tutorialURL', type='TEXT', notNull=false, primaryKeyPosition=0}, description=Column{name='description', type='TEXT', notNull=false, primaryKeyPosition=0}, eanBarcode=Column{name='eanBarcode', type='INTEGER', notNull=false, primaryKeyPosition=0}, id=Column{name='id', type='INTEGER', notNull=true, primaryKeyPosition=1}, name=Column{name='name', type='TEXT', notNull=false, primaryKeyPosition=0}, brandId=Column{name='brandId', type='INTEGER', notNull=false, primaryKeyPosition=0}, shadeId=Column{name='shadeId', type='INTEGER', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=[]}
```

**Comment by humazed** [comment]
As in #1 
Expected: the Dao class.
Found: The actual database.

columns order doesn't matter as long you ensures the types are the same

**Comment by MrLepage** [comment]
If you compare Expected and Found in my previous post you will see that the type are the same for each column.

Not null field is the same for each column too.

The only difference between the two is the order if the columns in TableInfo

**Comment by MrLepage** [comment]
I just see that "tutorialUrl" is expected with url in uppercase...

**Comment by humazed** [comment]
SQL should be case insensitive I'm not sure if it's your problem. 
try to rename to tutorialURL and let me know what happened

**Comment by MrLepage** [comment]
Thanks for making me check twice ;)

**Comment by MrLepage** [comment]
My Product Entity had the wrong column name.
Problem fixed.

**Comment by humazed** [comment]
interesting, so room is case sensitive.
glad you solve your problem.
